insert into book2user_type (id, code, name) values (1, 'ARCHIVED', 'В архиве');
insert into book2user_type (id, code, name) values (2, 'CART', 'В корзине');
insert into book2user_type (id, code, name) values (3, 'CART', 'В корзине');
insert into book2user_type (id, code, name) values (4, 'ARCHIVED', 'В архиве');
insert into book2user_type (id, code, name) values (5, 'KEPT', 'Отложена');
insert into book2user_type (id, code, name) values (6, 'PAID', 'Куплена');
insert into book2user_type (id, code, name) values (7, 'PAID', 'Куплена');
insert into book2user_type (id, code, name) values (8, 'ARCHIVED', 'В архиве');
insert into book2user_type (id, code, name) values (9, 'KEPT', 'Отложена');
insert into book2user_type (id, code, name) values (10, 'CART', 'В корзине');
insert into book2user_type (id, code, name) values (11, 'KEPT', 'Отложена');
insert into book2user_type (id, code, name) values (12, 'KEPT', 'Отложена');
insert into book2user_type (id, code, name) values (13, 'CART', 'В корзине');
insert into book2user_type (id, code, name) values (14, 'CART', 'В корзине');
insert into book2user_type (id, code, name) values (15, 'CART', 'В корзине');
insert into book2user_type (id, code, name) values (16, 'KEPT', 'Отложена');
insert into book2user_type (id, code, name) values (17, 'KEPT', 'Отложена');
insert into book2user_type (id, code, name) values (18, 'CART', 'В корзине');
insert into book2user_type (id, code, name) values (19, 'KEPT', 'Отложена');
insert into book2user_type (id, code, name) values (20, 'ARCHIVED', 'В архиве');
